version: '3.2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
    php:
        build: php7-fpm
        ports:
            - 9000:9000
        volumes:
            - ./symfony-demo:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes:
            - ./logs/symfony:/var/www/symfony/app/logs
            - ./logs/nginx/:/var/log/nginx
#    elk:
#        image: willdurand/elk
#        ports:
#            - 81:80
#        volumes:
#            - ./elk/logstash:/etc/logstash
#            - ./elk/logstash/patterns:/opt/logstash/patterns
    varnish:
        image: jonbaldie/varnish
        ports:
            - 8080:80
        environment:
          - BACKEND_APP=nginx
          - BACKEND_PORT=80
        volumes:
            - ./varnish/default.vcl:/etc/varnish/default.vcl
